### ISSUE TITLE
Order error

### ISSUE THREAD

**Issue by mzysk** [sjaakp/yii2-sortable-behavior#4]
Hi @sjaakp , thank you for great plugin, but i have one issue.

When i am sorting rows and saving with your action current position index it's working great. But if i am dragging for example five rows to same top i have five rows with order position = 0. They are not relative to each other so they are not sorted like on the list. 

I think that it should returning data about dragged row and also rearranged rows caused by last action.

Maybe i've just configured something wrong.

Thank you for your help.

Cheers.

**Comment by sjaakp** [comment]
Do you mean by dragging multiple items to the top? How do you manage that?

---

Sjaak Priester

 mailto:sjaak@sjaakpriester.nl sjaak@sjaakpriester.nl

Van: mzysk [mailto:notifications@github.com] 
Verzonden: dinsdag 7 juli 2015 23:41
Aan: sjaakp/yii2-sortable-behavior
CC: Sjaak Priester
Onderwerp: [yii2-sortable-behavior] Order error (#4)

Hi @sjaakp https://github.com/sjaakp  , thank you for great plugin, but i have one issue.

When i am sorting rows and saving with your action current position index it's working great. But if i am dragging for example five rows to same top i have five rows with order position = 0. They are not relative to each other so they are not sorted like on the list. 

I think that it should returning data about dragged row and also rearranged rows caused by last action.

Maybe i've just configured something wrong.

Thank you for your help.

Cheers.

**Comment by mzysk** [comment]
One by one. I just noticed that not every row in database tables are updated after sort callback. Only dragged row is updated in database.

**Comment by sjaakp** [comment]
Well, that’s not what should happen. Which database are you using?

---

Sjaak Priester

 mailto:sjaak@sjaakpriester.nl sjaak@sjaakpriester.nl

Van: mzysk [mailto:notifications@github.com] 
Verzonden: donderdag 9 juli 2015 12:33
Aan: sjaakp/yii2-sortable-behavior
CC: Sjaak Priester
Onderwerp: Re: [yii2-sortable-behavior] Order error (#4)

One by one. I just noticed that not every row in database tables are updated after sort callback. Only dragged row is updated in database.

**Comment by mzysk** [comment]
Mysql. Strange thing is that it's working great for other table. My sort column is 'sortorder' INT(10) default NULL.

I've added that behaviors to model:

```
public function behaviors( ) {
        return [
            [
                'class' => 'sjaakp\sortable\Sortable',
                'orderAttribute' => 'sortorder'
            ],
        ];
    }
```

and that's my action order:

```
public function actionOrder( )   {
        $post = Yii::$app->request->post( );
        if (isset( $post['key'], $post['pos'] ))   {
            $faqQuestion = FaqQuestions::findOne( $post['key'] );
            if ($faqQuestion) {
                $faqQuestion->order( $post['pos'] );
            }
        }
    }
```

in searchModel i have that query:

```
$query = FaqQuestions::find()->joinWith('relations')->orderBy(array('ISNULL(sortorder)' => SORT_ASC, 'sortorder' => SORT_ASC));
```

and dataprovider is default. My view file with gridview:

```
<?= SortableGridView::widget( [
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
        'filterSelector' => 'select[name="per-page"]',
    'orderUrl' => ['order'],
...
```
